### ISSUE TITLE
IPv6 unsupported

### ISSUE THREAD

**Issue by MakeItGreatAgain** [felixplesoianu/gophersnake#2]
Attempting to connect to an IPv6 address or a DNS name that with only an AAAA record gives an "Unknown address type." error message.

**Comment by MakeItGreatAgain** [comment]
Correction: "Errno 11001 getaddrinfo failed"

**Comment by felixp7** [comment]
Hi there! Thanks for letting me know. Sadly, working on Gophersnake is not a priority for me right now, so it may take a while.

**Comment by felixp7** [comment]
Fixed thanks to the patch by @madscientistninja -- thanks!
